
package com.ocewsd.binary.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SkiImageService", targetNamespace = "http://binary.soap.ocewsd.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkiImageService {


    /**
     * 
     * @return
     *     returns java.util.List<byte[]>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImages", targetNamespace = "http://binary.soap.ocewsd.com/", className = "com.ocewsd.binary.client.GetImages")
    @ResponseWrapper(localName = "getImagesResponse", targetNamespace = "http://binary.soap.ocewsd.com/", className = "com.ocewsd.binary.client.GetImagesResponse")
    @Action(input = "http://binary.soap.ocewsd.com/SkiImageService/getImagesRequest", output = "http://binary.soap.ocewsd.com/SkiImageService/getImagesResponse")
    public List<byte[]> getImages();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://binary.soap.ocewsd.com/", className = "com.ocewsd.binary.client.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://binary.soap.ocewsd.com/", className = "com.ocewsd.binary.client.GetImageResponse")
    @Action(input = "http://binary.soap.ocewsd.com/SkiImageService/getImageRequest", output = "http://binary.soap.ocewsd.com/SkiImageService/getImageResponse")
    public byte[] getImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
